title: Felling Tree Service
description: Turtle Lake, WI 54889 
baseurl: "/"
url: "https://fellingtreeservice.com/" 
remote_theme: jekyll/minima
skin: solarized
minima:
  social_links:
    - { platform: facebook, user_url: "https://www.facebook.com/Fellingtreeservice" }

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - docs/
  - node_modules
  - playwright-report